Take [], ()->
  Make "KeyName", KeyName = (e)->
    switch e.keyCode
      when 8 then "delete"
      when 9 then "tab"
      when 13 then "return"
      when 16 then "shift"
      when 17 then "control"
      when 18 then "option"
      when 20 then "caps lock"
      when 32 then "space"

      when 37 then "left"
      when 38 then "up"
      when 39 then "right"
      when 40 then "down"

      when 48 then "0"
      when 49 then "1"
      when 50 then "2"
      when 51 then "3"
      when 52 then "4"
      when 53 then "5"
      when 54 then "6"
      when 55 then "7"
      when 56 then "8"
      when 57 then "9"

      when 65 then "a"
      when 66 then "b"
      when 67 then "c"
      when 68 then "d"
      when 69 then "e"
      when 70 then "f"
      when 71 then "g"
      when 72 then "h"
      when 73 then "i"
      when 74 then "j"
      when 75 then "k"
      when 76 then "l"
      when 77 then "m"
      when 78 then "n"
      when 79 then "o"
      when 80 then "p"
      when 81 then "q"
      when 82 then "r"
      when 83 then "s"
      when 84 then "t"
      when 85 then "u"
      when 86 then "v"
      when 87 then "w"
      when 88 then "x"
      when 89 then "y"
      when 90 then "z"

      when 91 then "command" # left
      when 93 then "command" # right

      when 186 then "semicolon"
      when 187 then "equals"
      when 188 then "comma"
      when 189 then "minus"
      when 190 then "period"
      when 191 then "forward slash"
      when 192 then "tilde"
      when 219 then "left square bracket"
      when 220 then "backslash"
      when 221 then "right square bracket"
      when 222 then "quote"

      else e.key?.toLowerCase()
